#!/bin/bash
# APOS - Get Internshala Cookies for Video
# Run this in terminal to show cookie extraction

echo "=========================================="
echo "STEP 1: Get Internshala Cookies"
echo "=========================================="
echo ""
echo "Method 1 - CDP (Chrome DevTools Protocol):"
echo "  Terminal 1:"
echo "    /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222 --user-data-dir=/tmp/chrome_debug"
echo ""
echo "  Terminal 2:"
echo "    python get_cookies.py --cdp"
echo ""
echo "Method 2 - Playwright (EASIER, shows browser):"
echo "    python get_cookies.py --browser"
echo ""
echo "=========================================="
echo "What happens:"
echo "=========================================="
echo "  1. Browser opens (visible)"
echo "  2. Navigate to internshala.com/login"
echo "  3. YOU log in manually"
echo "  4. Go to applications page"
echo "  5. Press ENTER"
echo "  6. Cookies saved to data/cookies.json"
echo ""
echo "=========================================="
echo "After getting cookies, run:"
echo "=========================================="
echo "  python test_system.py   # Test everything"
echo "  python demo_run.py       # Full demo"
echo ""
echo "Or test Internshala scraping:"
echo "  python access_internshala.py"
echo "=========================================="